alert("Oiiee, meu amor!")
alert("Vc tem certeza que vc quer acessar isso??")
alert("Se n tiver, eu acho que é melhor sair, viu?")
alert("Aqui vc pode ver coisas que vc pode nunca ter imaginado antes...")
alert("Ta bom, já q vc chegou até aqui... eu vou revelar vai...")
alert("Trêss.....")
alert("Doisss.....")
alert("Ummm....")
alert("Ihhhh.....")
alert("Tcharammm.....")
alert("É, meu amor, n era nada :(, sinto muito")
alert("Talvez da próxima vez tenha algo maior")
alert("Espera, o quê??? Vc ainda está aqui??")
alert("Oh céus, ela vai descobrirrrr")
alert("Ta bom, vai, aperta OK ai então")
let nome = prompt('Espera, antes de liberar... qual é o seu nome??');
let idade = prompt('Tá bom, vc pode passar, mas quantos anos vc tem??');
alert("Desculpa tá kkk, é que eu fiquei com medo de outra pessoa entrasse aqui... xD")
let niver =prompt("Taaa, última pergunta, qual é o nosso aniversário de namoro??")
alert("Okaayyyy, meio suspeito issooo....")
alert("Mas tudo bem, pode acessar vai...")